version: "3.8"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.prod
    
    container_name: f1-app-prod
    
    ports:
      - '5174:80'  # Map host 5174 to nginx port 80
    
    restart: unless-stopped
    
    networks:
      - f1-network

networks:
  f1-network:
    external: true